global using E_Commerce.Domain.Contracts;
global using E_Commerce.Domain.Entities;
global using E_Commerce.Infrastructure.Data;
global using E_Commerce.Infrastructure.Repositories;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using StackExchange.Redis;